on: push
name: Build and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Test
      run: npm test
    - name: Publish
      uses: mikeal/merge-release@master
      if: github.ref == 'refs/heads/master' && github.repository == 'mikeal/csv-merge'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
